<?php
Route::post('/product/get','App\Http\Controllers\Admin\ProductController@get');
Route::post('/product/getByLiveSearch','App\Http\Controllers\Admin\ProductController@getByLiveSearch');
Route::post('/product/store','App\Http\Controllers\Admin\ProductController@store');
Route::post('/product/edit','App\Http\Controllers\Admin\ProductController@edit');
Route::post('/product/upload_image','App\Http\Controllers\Admin\ProductController@uploadImage');
Route::post('/product/copy','App\Http\Controllers\Admin\ProductController@copy');
Route::post('/product/delete','App\Http\Controllers\Admin\ProductController@delete');
Route::post('/product/print','App\Http\Controllers\Admin\ProductController@print');
Route::post('/product/printLabel','App\Http\Controllers\Admin\ProductController@printLabel');
